"""added presence check to calendar

Revision ID: b10d53adee8f
Revises: db871ba69fc4
Create Date: 2024-12-26 14:50:22.135344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10d53adee8f'
down_revision: Union[str, None] = 'db871ba69fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remote_days', sa.Column('present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remote_days', 'present')
    # ### end Alembic commands ###
