"""add hours_worked to tasks

Revision ID: d7637ea98fc3
Revises: dbd7a6e1463c
Create Date: 2024-11-20 14:02:12.736837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7637ea98fc3'
down_revision: Union[str, None] = 'dbd7a6e1463c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('hours_worked', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'hours_worked')
    # ### end Alembic commands ###
