"""added user_name to task

Revision ID: e32c83b8d40c
Revises: 2cb6659531f8
Create Date: 2024-11-19 02:50:49.214145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32c83b8d40c'
down_revision: Union[str, None] = '2cb6659531f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_name')
    # ### end Alembic commands ###
