"""Added user_name to logs

Revision ID: ef09f0b51487
Revises: 1edfcd75e4f7
Create Date: 2024-12-17 04:28:29.421418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef09f0b51487'
down_revision: Union[str, None] = '1edfcd75e4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_log', sa.Column('user_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_log', 'user_name')
    # ### end Alembic commands ###
