from typing import Any, List, Type, Generic, TypeVar, Optional, Protocol

T = TypeVar("T")


class ISession(Protocol, Generic[T]):
    def add(self, obj: T) -> None: ...

    def get(self, model: Type[T], id: Any) -> Optional[T]: ...

    def update(self, obj: T) -> None: ...

    def delete(self, obj: T) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def query(self, model: Type[T], *args, **kwargs) -> List[T]: ...
